#
# Definition of the OpenStack environment variables
#
variables:
    openstack_user_name: <openstack_user_name>
    openstack_tenant_name: <openstack_tenant_name>
    openstack_password: <openstack_password>
    openstack_auth_url: <openstack_auth_url>
    openstack_region: <openstack_region>
    openstack_domain_name: <openstack_domain_name>
    base_image: <base_image>
    ssh_key_pair: <ssh_key_pair>
    ssh_user_name: <ssh_user_name>
    availability_zone: <availability_zone>
    external_pool: <external_pool>

vms:
  vm1:
    id: <id>
    name: <name>
    description: <description>
    flavour: <flavour>

  vm2:
    id: <id>
    name: <name>
    description: <description>
    flavour: <flavour>

  <...>

volumes:
  vol1:
    name: <name>
    description: <description>
    size: <size>
    vm: <vm>

  vol2:
    name: <name>
    description: <description>
    size: <size>
    vm: <vm>

  <...>